on:
  workflow_call:

jobs:
  build_win_32:
    name: 'Windows (x86)'
    runs-on: windows-latest
    timeout-minutes: 60
    env:
      IncludeUwp: 'true'
    steps:
    - uses: actions/checkout@v4
    - name: Build CPython
      run: .\PCbuild\build.bat -e -d -p Win32
    - name: Display build info
      run: .\python.bat -m test.pythoninfo
    - name: Tests
      run: .\PCbuild\rt.bat -p Win32 -d -q --fast-ci

  build_win_amd64:
    name: 'Windows (x64)'
    runs-on: windows-latest
    timeout-minutes: 60
    env:
       IncludeUwp: 'true'
    steps:
    - uses: actions/checkout@v4
    - name: Register MSVC problem matcher
      run: echo "::add-matcher::.github/problem-matchers/msvc.json"
    - name: Build CPython
      run: .\PCbuild\build.bat -e -d -p x64
    - name: Display build info
      run: .\python.bat -m test.pythoninfo
    - name: Tests
      run: .\PCbuild\rt.bat -p x64 -d -q --fast-ci

  build_win_arm64:
    name: 'Windows (arm64)'
    runs-on: windows-latest
    timeout-minutes: 60
    env:
      IncludeUwp: 'true'
    steps:
    - uses: actions/checkout@v4
    - name: Register MSVC problem matcher
      run: echo "::add-matcher::.github/problem-matchers/msvc.json"
    - name: Build CPython
      run: .\PCbuild\build.bat -e -d -p arm64
